#!/bin/bash
## set -x
. ./layers.slc
check_root_status() {
	if [[ `whoami` == "root" ]]; then
		echo "you are running in root mode, please rerun in non-root mode"
		exit 85
	fi
}

check_system_codename() {
	##
	if [[ -f /etc/os-release ]]; then
		. /etc/os-release
		if [[ $ID == "debian" && $VERSION_ID == "8" ]]; then
			VERSION_CODENAME=jessie
		elif [[ $ID == "debian" && VERSION_ID == "9" ]]; then
			VERSION_CODENAME=stretch
		else
			export VERSION_CODENAME
		fi
	##
	elif type lsb_release >/dev/null 2>&1; then
		VERSION_CODENAME=`lsb_release -cs`
		export VERSION_CODENAME
	##
	elif [[ -f /etc/lsb-release ]]; then
		. /etc/lsb-release
		VERSION_CODENAME=$DISTRIB_CODENAME
		export VERSION_CODENAME
	fi
}

distrubuted_check() {
	for layer in $Layers; do
		echo checking 
		echo $layer
		. ./layers/$layer/check.sh;
	done
}

check_root_status
check_system_codename
distrubuted_check
