#!/bin/bash
## this file generates come variables for later use
## set -x
. ./layers.slc

config_source_ubuntu() {
	echo choose the suitable source
	echo '0) azure 1) ustc'
	echo default to no change
	read SOURCE_NUMBER
	if [[ $SOURCE_NUMBER == 0 ]]; then
		sudo cp ./sources/azure/$VERSION_CODENAME /etc/apt/sources.list
	elif [[ $SOURCE_NUMBER == 1 ]]; then
		sudo cp ./sources/ustc/$VERSION_CODENAME /etc/apt/sources.list
	fi
	sudo apt update
}

distributed_config() {
	for layer in $Layers; do
		. ./layers/$layer/config.sh
	done
}

config_source_ubuntu
distributed_config
